import type {
  Cycle,
  Invite,
  KeyResult,
  KrUpdate,
  Objective,
  Organization,
  Profile,
  Team,
  WeeklyProgress,
  KyliaData,
} from "./types";

export const organization: Organization = {
  id: "org_kynovia",
  name: "Kynovia",
  slug: "kynovia",
  sector: "AI products and business performance",
  plan: "growth",
  maxUsers: 25,
};

export const profiles: Profile[] = [
  {
    id: "ana",
    fullName: "Ana Ribeiro",
    email: "ana@kynovia.ai",
    jobTitle: "CEO",
    role: "admin",
    teamIds: ["leadership"],
  },
  {
    id: "marcos",
    fullName: "Marcos Lima",
    email: "marcos@kynovia.ai",
    jobTitle: "Head de Produto",
    role: "team_lead",
    teamIds: ["product"],
  },
  {
    id: "bia",
    fullName: "Bia Nunes",
    email: "bia@kynovia.ai",
    jobTitle: "Revenue Lead",
    role: "team_lead",
    teamIds: ["sales"],
  },
  {
    id: "leo",
    fullName: "Leo Castro",
    email: "leo@kynovia.ai",
    jobTitle: "Customer Success",
    role: "member",
    teamIds: ["success"],
  },
];

export const teams: Team[] = [
  {
    id: "leadership",
    name: "Empresa",
    description: "OKRs corporativos e alinhamento executivo",
    color: "#7EBF8E",
    leadId: "ana",
    isActive: true,
  },
  {
    id: "product",
    name: "Produto",
    description: "Experiência, ativação e entrega do MVP",
    color: "#6DBBE8",
    leadId: "marcos",
    isActive: true,
  },
  {
    id: "sales",
    name: "Receita",
    description: "Pipeline, vendas e expansão",
    color: "#E8B86D",
    leadId: "bia",
    isActive: true,
  },
  {
    id: "success",
    name: "Sucesso",
    description: "Onboarding, saúde e retenção de clientes",
    color: "#B08AE8",
    leadId: "leo",
    isActive: true,
  },
];

export const cycles: Cycle[] = [
  {
    id: "q2_2026",
    name: "Q2 2026",
    type: "quarterly",
    startDate: "2026-04-01",
    endDate: "2026-06-30",
    isActive: true,
  },
  {
    id: "annual_2026",
    name: "Anual 2026",
    type: "annual",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    isActive: false,
  },
];

export const objectives: Objective[] = [
  {
    id: "obj_company_growth",
    cycleId: "q2_2026",
    teamId: "leadership",
    title: "Transformar OKRs em rotina executiva semanal",
    description: "Garantir que liderança e times usem uma unica fonte de verdade para foco, progresso e bloqueios.",
    ownerId: "ana",
    progress: 68,
    status: "at_risk",
    isCompanyOkr: true,
  },
  {
    id: "obj_product_activation",
    cycleId: "q2_2026",
    teamId: "product",
    parentId: "obj_company_growth",
    title: "Criar uma experiência de ativação simples e confiável",
    description: "Reduzir atrito para configurar organização, ciclo, times, objetivos e primeiros KRs.",
    ownerId: "marcos",
    progress: 76,
    status: "on_track",
    isCompanyOkr: false,
  },
  {
    id: "obj_revenue_pipeline",
    cycleId: "q2_2026",
    teamId: "sales",
    parentId: "obj_company_growth",
    title: "Validar o modelo comercial com clientes beta",
    description: "Construir pipeline qualificado e converter contratos piloto em contas pagas.",
    ownerId: "bia",
    progress: 52,
    status: "at_risk",
    isCompanyOkr: false,
  },
  {
    id: "obj_success_health",
    cycleId: "q2_2026",
    teamId: "success",
    parentId: "obj_company_growth",
    title: "Aumentar previsibilidade dos check-ins de clientes",
    description: "Padronizar acompanhamento semanal, alertas e planos de desbloqueio.",
    ownerId: "leo",
    progress: 34,
    status: "behind",
    isCompanyOkr: false,
  },
];

export const keyResults: KeyResult[] = [
  {
    id: "kr_exec_checkins",
    objectiveId: "obj_company_growth",
    title: "Realizar check-in executivo em 10 de 12 semanas",
    description: "Registro semanal de progresso, riscos e decisões do comitê executivo.",
    ownerId: "ana",
    krType: "numeric",
    startValue: 0,
    targetValue: 12,
    currentValue: 8,
    unit: "semanas",
    progress: 67,
    status: "at_risk",
    confidence: 7,
    sortOrder: 1,
    lastUpdate: "2026-04-24",
  },
  {
    id: "kr_org_health",
    objectiveId: "obj_company_growth",
    title: "Manter 85% dos KRs atualizados nos ultimos 7 dias",
    description: "Reduzir KRs stale e aumentar confiabilidade do dashboard.",
    ownerId: "ana",
    krType: "percentage",
    startValue: 30,
    targetValue: 85,
    currentValue: 66,
    unit: "%",
    progress: 65,
    status: "at_risk",
    confidence: 6,
    sortOrder: 2,
    lastUpdate: "2026-04-22",
  },
  {
    id: "kr_first_value",
    objectiveId: "obj_product_activation",
    title: "Levar novo admin ao primeiro objetivo criado em ate 8 minutos",
    description: "Fluxo de onboarding com organização, time, ciclo e objetivo inicial.",
    ownerId: "marcos",
    krType: "numeric",
    startValue: 22,
    targetValue: 8,
    currentValue: 11,
    unit: "min",
    progress: 79,
    status: "on_track",
    confidence: 8,
    sortOrder: 1,
    lastUpdate: "2026-04-26",
  },
  {
    id: "kr_update_completion",
    objectiveId: "obj_product_activation",
    title: "Atingir 90% de conclusão no modal de update de KR",
    description: "Atualização de valor, comentário, confiança e bloqueio sem perda de contexto.",
    ownerId: "marcos",
    krType: "percentage",
    startValue: 40,
    targetValue: 90,
    currentValue: 82,
    unit: "%",
    progress: 84,
    status: "on_track",
    confidence: 8,
    sortOrder: 2,
    lastUpdate: "2026-04-25",
  },
  {
    id: "kr_beta_pipeline",
    objectiveId: "obj_revenue_pipeline",
    title: "Gerar R$ 120 mil em pipeline beta qualificado",
    description: "Empresas com dor clara em alinhamento e cadência de OKRs.",
    ownerId: "bia",
    krType: "currency",
    startValue: 0,
    targetValue: 120000,
    currentValue: 62000,
    unit: "R$",
    progress: 52,
    status: "at_risk",
    confidence: 5,
    sortOrder: 1,
    lastUpdate: "2026-04-19",
    hasBlocker: true,
  },
  {
    id: "kr_paid_pilots",
    objectiveId: "obj_revenue_pipeline",
    title: "Converter 6 clientes em piloto pago",
    description: "Contratos pequenos com ciclo trimestral e sucesso assistido.",
    ownerId: "bia",
    krType: "numeric",
    startValue: 0,
    targetValue: 6,
    currentValue: 3,
    unit: "clientes",
    progress: 50,
    status: "at_risk",
    confidence: 6,
    sortOrder: 2,
    lastUpdate: "2026-04-21",
  },
  {
    id: "kr_customer_checkins",
    objectiveId: "obj_success_health",
    title: "Completar 95% dos check-ins semanais com clientes ativos",
    description: "Ritual de acompanhamento com status, próximos passos e bloqueios.",
    ownerId: "leo",
    krType: "percentage",
    startValue: 45,
    targetValue: 95,
    currentValue: 63,
    unit: "%",
    progress: 36,
    status: "behind",
    confidence: 4,
    sortOrder: 1,
    lastUpdate: "2026-04-16",
    hasBlocker: true,
  },
  {
    id: "kr_risk_playbooks",
    objectiveId: "obj_success_health",
    title: "Criar playbooks para os 5 bloqueios mais recorrentes",
    description: "Ações sugeridas para times, ciclos vencidos, KRs atrasados, baixa confiança e falta de dono.",
    ownerId: "leo",
    krType: "numeric",
    startValue: 0,
    targetValue: 5,
    currentValue: 2,
    unit: "playbooks",
    progress: 40,
    status: "at_risk",
    confidence: 5,
    sortOrder: 2,
    lastUpdate: "2026-04-17",
  },
];

export const updates: KrUpdate[] = [
  {
    id: "upd_1",
    keyResultId: "kr_beta_pipeline",
    updatedBy: "bia",
    previousValue: 50000,
    newValue: 62000,
    progress: 52,
    confidence: 5,
    comment: "Pipeline avançou, mas duas contas aguardam aprovação jurídica.",
    hasBlocker: true,
    blockerDescription: "Ciclo de contratação mais longo que o previsto.",
    createdAt: "2026-04-19",
  },
  {
    id: "upd_2",
    keyResultId: "kr_customer_checkins",
    updatedBy: "leo",
    previousValue: 58,
    newValue: 63,
    progress: 36,
    confidence: 4,
    comment: "Melhoramos agenda, ainda falta padronizar follow-up.",
    hasBlocker: true,
    blockerDescription: "Times internos sem dono claro para alguns clientes.",
    createdAt: "2026-04-16",
  },
];

export const invites: Invite[] = [
  {
    id: "invite_1",
    email: "camila@cliente.com",
    role: "team_lead",
    accepted: false,
    expiresAt: "2026-05-02",
  },
  {
    id: "invite_2",
    email: "financeiro@kynovia.ai",
    role: "member",
    accepted: true,
    expiresAt: "2026-04-29",
  },
];

export const weeklyProgress: WeeklyProgress[] = [
  { week: "01/abr", company: 48, product: 55, sales: 31, success: 42 },
  { week: "08/abr", company: 54, product: 61, sales: 39, success: 44 },
  { week: "15/abr", company: 59, product: 67, sales: 45, success: 38 },
  { week: "22/abr", company: 64, product: 72, sales: 49, success: 35 },
  { week: "27/abr", company: 68, product: 76, sales: 52, success: 34 },
];

export const demoData: KyliaData = {
  organization,
  profiles,
  teams,
  cycles,
  objectives,
  keyResults,
  updates,
  invites,
  weeklyProgress,
};
